const express = require("express");
const SSLCommerzPayment = require("sslcommerz-lts");

const createPaymentRouter = (paymentsCollection, assetsCollection) => {
    const router = express.Router();

    const store_id = process.env.SSL_STORE_ID;
    const store_passwd = process.env.SSL_STORE_PASSWORD;
    const is_live = false; // Set to true for production/live environment

    // 1. INIT PAYMENT (Called from your frontend checkout button)
    router.post("/init", async (req, res) => {
        try {
            const { tran_id, total_amount, cus_name, cus_email, cus_phone } = req.body;

            const data = {
                total_amount: total_amount || 1000,
                currency: "BDT",
                tran_id: tran_id, // Unique transaction ID generated by client/server
                success_url: `http://localhost:5000/api/payment/success/${tran_id}`,
                fail_url: `http://localhost:5000/api/payment/fail/${tran_id}`,
                cancel_url: `http://localhost:5000/api/payment/cancel/${tran_id}`,
                ipn_url: `http://localhost:5000/api/payment/ipn`,
                shipping_method: "No",
                product_name: "Asset Plan Upgrade",
                product_category: "Subscription",
                product_profile: "general",
                cus_name: cus_name || "User",
                cus_email: cus_email || "user@gmail.com",
                cus_add1: "Dhaka",
                cus_country: "Bangladesh",
                cus_phone: cus_phone || "01700000000",
            };

            const sslcz = new SSLCommerzPayment(store_id, store_passwd, is_live);
            
            sslcz.init(data).then((apiResponse) => {
                let GatewayPageURL = apiResponse.GatewayPageURL;
                if (GatewayPageURL) {
                    res.json({ url: GatewayPageURL });
                } else {
                    res.status(400).json({ error: "Failed to connect with SSLCommerz gateway." });
                }
            });
        } catch (error) {
            console.error("❌ Payment Init Error:", error);
            res.status(500).json({ error: "Internal server error during payment initialization." });
        }
    });

    // 2. SUCCESS CALLBACK (Redirected here by SSLCommerz after successful payment)
    router.post("/success/:tran_id", async (req, res) => {
        try {
            const { tran_id } = req.params;
            const validationPayload = req.body; // Contains val_id

            const sslcz = new SSLCommerzPayment(store_id, store_passwd, is_live);
            
            // CRITICAL: Validate the transaction with SSLCommerz server before trusting it
            const validationResponse = await sslcz.validate(validationPayload);

            if (validationResponse.status === 'VALID' || validationResponse.status === 'VALIDATED') {
                // Payment is 100% genuine! Update your database here.
                console.log(`✅ Payment Validated for Transaction: ${tran_id}`);

                // Example: Record the transaction in a separate payment collection
                await paymentsCollection.insertOne({
                    tran_id,
                    val_id: validationPayload.val_id,
                    amount: validationResponse.amount,
                    status: "SUCCESS",
                    paidAt: new Date().toISOString(),
                    customerEmail: validationResponse.cus_email
                });

                // TODO: Update user's feature tier / status logic here 
                // e.g., upgrading their permission or workspace flag

                // Redirect user back to your frontend success page
                res.redirect(`http://localhost:5173/dashboard?payment=success&tran_id=${tran_id}`);
            } else {
                // 🛠️ FIXED: Corrected error syntax object declaration
                res.status(400).json({ error: "Payment validation failed." });
            }
        } catch (error) {
            console.error("❌ Success Callback Error:", error);
            res.status(500).json({ error: "Payment verification failed." });
        }
    });

    // 3. FAIL CALLBACK
    router.post("/fail/:tran_id", async (req, res) => {
        const { tran_id } = req.params;
        console.log(`⚠️ Payment Failed for Transaction: ${tran_id}`);
        res.redirect(`http://localhost:5173/dashboard?payment=fail&tran_id=${tran_id}`);
    });

    // 4. CANCEL CALLBACK
    router.post("/cancel/:tran_id", async (req, res) => {
        const { tran_id } = req.params;
        console.log(`⚠️ Payment Cancelled for Transaction: ${tran_id}`);
        res.redirect(`http://localhost:5173/dashboard?payment=cancel&tran_id=${tran_id}`);
    });

    return router;
};

module.exports = createPaymentRouter;